apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-webapp
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 5
      maxUnavailable: 0
  replicas: 10
  template:
    spec:
      containers:
      - image: angular-node-webapp:v1.16.2
        name: webapp