apiVersion: v1
kind: Service
metadata:
  name: {{.Values.application.name}}
  labels:
    run: angular-webapp
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
  selector:
    app: angular-webapp
  type: NodePort