# Default values for my-node-js-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: angular-node-webapp
  pullPolicy: Never
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

application:
  name: angular-webapp

service:
  port: 3080