apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmChartInflationGenerator:
- chartName: mongodb
  chartRepoUrl: https://charts.bitnami.com/bitnami
  #chartVersion: 6.0.2
  releaseNamespace: angular-app-development
  releaseName: my-mongodb
  #valuesFile: values.yam
